const NOTES = Object.assign({}, window.NOTES_PART1, window.NOTES_PART2, window.NOTES_PART3, window.NOTES_PART4);
const GROUPS = [
  { name: "Mathematics", description: "Core numeracy, reasoning and problem solving taken by every learner.", subjects: ["Mathematics"], icon: '<path d="M4 7h7M7.5 3.5v7M4 17h7M4 20.5h7M14 5.5l6 6M20 5.5l-6 6M14 17.5h6M14 20.5h6" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>' },
  { name: "Languages", description: "Communication, reading, writing and language development.", subjects: ["English", "Kiswahili", "Arabic", "French", "German"], icon: '<path d="M4 6h10M4 11h7M13 20l5-12 5 12M15.5 16h5" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>' },
  { name: "Pure Sciences", description: "Scientific understanding, investigation and evidence-based thinking.", subjects: ["Biology", "Chemistry", "Physics"], icon: '<path d="M9 3h6M10 3v6l-5 9a3 3 0 0 0 2.7 4.3h8.6A3 3 0 0 0 19 18l-5-9V3M7.5 15h9" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>' },
  { name: "Applied Sciences", description: "Science and technology applied to everyday life, health and practical problem-solving.", subjects: ["Agriculture", "Home Science", "Computer Studies"], icon: '<path d="M12 21c4.5-2 7-5.5 7-10V5l-7-2-7 2v6c0 4.5 2.5 8 7 10z" stroke="currentColor" stroke-width="2" fill="none"/><path d="M9 11l2.2 2.3L15.5 9" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>' },
  { name: "Humanities", description: "People, places, history, citizenship and society.", subjects: ["History and Government", "Geography", "Business Studies"], icon: '<circle cx="12" cy="12" r="9" stroke="currentColor" stroke-width="2" fill="none"/><path d="M3 12h18M12 3c3 3.5 3 14.5 0 18M12 3C9 6.5 9 17.5 12 21" stroke="currentColor" stroke-width="2" fill="none"/>' },
  { name: "Religious Education", description: "Faith, values, ethics and responsible participation in society.", subjects: ["Christian Religious Education", "Islamic Religious Education", "Hindu Religious Education"], icon: '<path d="M12 3v18M6 9h12M4 21h16" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>' },
  { name: "Arts & Sports", description: "Creative expression, performance, wellbeing and physical development.", subjects: ["Art and Design", "Music", "Sports and Physical Education"], icon: '<circle cx="8" cy="17" r="3.5" stroke="currentColor" stroke-width="2" fill="none"/><path d="M11.5 17V5l8-2v11.5" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/><circle cx="17" cy="16" r="3" stroke="currentColor" stroke-width="2" fill="none"/>' },
  { name: "Technical Studies", description: "Design, making, digital skills and practical career-oriented learning.", subjects: ["Technical Studies", "Building and Construction", "Electricity", "Woodwork", "Metalwork"], icon: '<path d="M14.5 3.5a4.5 4.5 0 0 0 5.8 6L21 10.8 13.2 18.6l-3.8 3.8-2.8-2.8 3.8-3.8L18.2 8" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/><path d="M6 3l4 4-2 2-4-4z" stroke="currentColor" stroke-width="2" fill="none"/>' }
];
const RESOURCES = [
  { name: "KICD curriculum designs", description: "Official curriculum-design landing page for regular and special-needs learners.", url: "https://kicd.ac.ke/curriculum-designs/", source: "Kenya Institute of Curriculum Development" },
  { name: "KICD Grade 10 designs", description: "Official Grade 10 learning-area pages.", url: "https://kicd.ac.ke/cbc-materials/curriculum-designs/grade-ten/", source: "Kenya Institute of Curriculum Development" },
  { name: "KICD Grade 11 designs", description: "Official Grade 11 learning-area pages.", url: "https://kicd.ac.ke/cbc-materials/curriculum-designs/grade-eleven/", source: "Kenya Institute of Curriculum Development" },
  { name: "Secondary syllabus collection", description: "A subject-by-subject syllabus index. Use KICD as the authoritative reference where versions differ.", url: "https://educationnewshub.co.ke/syllabus-for-all-secondary-schools-per-subjects-latest-syllabus/", source: "Education News Hub" }
];
const SOMASMART_URL = window.location.origin;
const esc = (s) => String(s).replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c]));
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const somaSmartUrl = (subject) => `${SOMASMART_URL}/?subject=${encodeURIComponent(subject)}&from=curriculum-guide`;
document.querySelectorAll('a[href^="http://127.0.0.1:5000"]').forEach((link) => { link.href = "/"; });
let theme = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
function applyTheme() { document.documentElement.setAttribute("data-theme", theme); document.getElementById("themeicon").innerHTML = theme === "dark" ? '<path d="M20 14.5A8.5 8.5 0 0 1 9.5 4a8.5 8.5 0 1 0 10.5 10.5z"/>' : '<circle cx="12" cy="12" r="4.5"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5L19 19M19 5l-1.5 1.5M6.5 17.5L5 19"/>'; }
document.getElementById("theme").addEventListener("click", () => { theme = theme === "dark" ? "light" : "dark"; applyTheme(); }); applyTheme();
function renderHome() {
  document.getElementById("grouplist").innerHTML = GROUPS.map((g) => `<article class="group"><div class="glyph"><svg width="28" height="28" viewBox="0 0 24 24" aria-hidden="true">${g.icon}</svg></div><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p><div class="chips">${g.subjects.map((s) => `<button class="chip" data-s="${esc(s)}">${esc(s)}</button>`).join("")}</div></article>`).join("");
  document.getElementById("reslist").innerHTML = RESOURCES.map((r) => `<a class="res" href="${r.url}" target="_blank" rel="noopener"><strong>${esc(r.name)}</strong><p>${esc(r.description)}</p><em>${esc(r.source)}</em></a>`).join("");
  const subs = Object.keys(NOTES); let strands = 0, qs = 0; subs.forEach((s) => { strands += NOTES[s].strands.length; qs += NOTES[s].questions.length; }); document.getElementById("ngrp").textContent = GROUPS.length; document.getElementById("nsub").textContent = subs.length; document.getElementById("nstrand").textContent = strands; document.getElementById("nq").textContent = qs;
  document.getElementById("grouplist").addEventListener("click", (e) => { const b = e.target.closest("[data-s]"); if (b) location.hash = "#" + slug(b.dataset.s); });
}
function groupOf(subject) { const g = GROUPS.find((x) => x.subjects.includes(subject)); return g ? g.name : ""; }
function renderSubject(name) {
  const d = NOTES[name]; const el = document.getElementById("subject");
  el.innerHTML = `<nav class="crumbs"><button onclick="goHome()">All learning areas</button><span>/</span><span>${esc(groupOf(name))}</span></nav><header class="subject-head"><span class="eyebrow">${esc(groupOf(name))}</span><h1>${esc(name)}</h1><p>${esc(d.tagline)}</p><p><a class="btn btn-ghost" href="${somaSmartUrl(name)}" target="_blank" rel="noopener">Continue ${esc(name)} practice in SomaSmart ↗</a></p></header><div class="layout"><aside class="toc"><h4>Strands</h4>${d.strands.map((s, i) => `<a href="#st-${i}">${esc(s.name)}</a>`).join("")}<a href="#lesson-builder">Lesson builder</a></aside><div>${d.strands.map((s, i) => `<section class="strand" id="st-${i}"><span class="strand-no">Strand ${i + 1}</span><h3>${esc(s.name)}</h3><ul>${s.notes.map((n) => `<li>${esc(n)}</li>`).join("")}</ul></section>`).join("")}<div class="panel"><h3>Key terms to master</h3><div class="termlist">${d.terms.map((t) => `<span class="term">${esc(t)}</span>`).join("")}</div></div><div class="panel"><h3>Revision and practice tasks</h3><ol>${d.questions.map((q, k) => `<li>${esc(q)}${(d.worked && d.worked[k]) ? `<details class="solution"><summary>Show worked solution</summary><ol class="steps">${d.worked[k].map((s) => `<li>${esc(s)}</li>`).join("")}</ol></details>` : ""}</li>`).join("")}</ol></div><div class="panel" id="lesson-builder"><h3>Build a lesson</h3><div class="builder"><div class="builder-form"><label class="field"><span>Strand</span><select id="lb-strand">${d.strands.map((s, i) => `<option value="${i}">${esc(s.name)}</option>`).join("")}</select></label><label class="field"><span>Grade / class</span><select id="lb-grade"><option>Grade 10</option><option>Grade 11</option><option>Grade 12</option><option>Form 3</option><option>Form 4</option></select></label><label class="field"><span>Lesson length</span><select id="lb-time"><option>40 minutes</option><option>80 minutes (double)</option></select></label><button class="btn btn-primary" id="lb-go" type="button">Generate lesson plan</button></div><div class="lesson-out" id="lb-out"><p class="empty">Choose a strand and generate a plan with objectives, activities, resources and assessment.</p></div></div></div></div></div>`;
  document.getElementById("lb-go").addEventListener("click", () => buildLesson(name)); document.body.classList.add("view-subject"); window.scrollTo(0, 0);
}
function buildLesson(name) {
  const d = NOTES[name], i = +document.getElementById("lb-strand").value, strand = d.strands[i], grade = document.getElementById("lb-grade").value, time = document.getElementById("lb-time").value, double = time.startsWith("80"), t = (a, b) => double ? b : a;
  const topics = strand.notes.filter((n) => n.includes(":" )).map((n) => n.split(":")[0].trim().replace(/^[A-Z]/, (c) => c.toLowerCase())).slice(0, 3); const verbs = ["explain", "describe", "discuss"]; const objectives = topics.map((x, k) => `${verbs[k]} ${x}`); const fallback = [`outline the key ideas covered in ${strand.name.toLowerCase()}`, `apply ${strand.name.toLowerCase()} to familiar examples`, `appreciate the value of ${strand.name.toLowerCase()} in everyday life`]; while (objectives.length < 3) objectives.push(fallback[objectives.length]); const q = d.questions[i % d.questions.length];
  document.getElementById("lb-out").innerHTML = `<h4>Lesson details</h4><p><strong>${esc(name)}</strong> — ${esc(strand.name)}<br>${esc(grade)} · ${esc(time)}</p><h4>Specific learning outcomes</h4><p>By the end of the lesson the learner should be able to:</p><ul>${objectives.map((o) => `<li>${esc(o)};</li>`).join("")}</ul><h4>Lesson flow</h4><ul><li><strong>Introduction (${t(5, 8)} min):</strong> review prior knowledge and pose a real-life question.</li><li><strong>Development step 1 (${t(10, 20)} min):</strong> teacher-guided discussion of ${esc(strand.name.toLowerCase())}.</li><li><strong>Development step 2 (${t(12, 25)} min):</strong> group task, practical activity or worked examples.</li><li><strong>Learner presentation (${t(8, 15)} min):</strong> groups report findings and correct misconceptions.</li><li><strong>Conclusion (${t(5, 12)} min):</strong> summary, key terms recap and assignment.</li></ul><h4>Core competencies and values</h4><p>Communication and collaboration, critical thinking and problem solving, digital literacy; respect, responsibility and integrity.</p><h4>Resources</h4><p>Approved course book, KICD curriculum design for ${esc(name)}, charts or realia, learner exercise books${double ? ", laboratory or workshop materials where applicable" : ""}.</p><h4>Assessment</h4><ul><li>Oral questions and observation of group work.</li><li>Written exercise: ${esc(q)}</li><li>Key terms checked: ${esc(d.terms.slice(0, 3).join(", "))}.</li></ul><h4>Reflection</h4><p>Note which learners needed support, what to reteach, and the adjustment for the next lesson.</p><p style="margin-top:var(--space-5)"><button class="btn btn-ghost" type="button" onclick="window.print()">Print or save as PDF</button></p>`;
}
const qEl = document.getElementById("q"), qres = document.getElementById("qres");
function search(term) { term = term.trim().toLowerCase(); if (term.length < 2) { qres.classList.remove("on"); return; } const out = []; Object.keys(NOTES).forEach((s) => { if (s.toLowerCase().includes(term)) out.push({ s, label: s, sub: "Subject notes" }); NOTES[s].strands.forEach((st, i) => { if (st.name.toLowerCase().includes(term)) out.push({ s, label: st.name, sub: `${s} · strand ${i + 1}`, anchor: `st-${i}` }); else if (st.notes.join(" ").toLowerCase().includes(term)) out.push({ s, label: st.name, sub: `${s} · mentions “${term}”`, anchor: `st-${i}` }); }); }); qres.innerHTML = out.length ? out.slice(0, 20).map((r) => `<button data-s="${esc(r.s)}" data-a="${esc(r.anchor || "")}">${esc(r.label)}<em>${esc(r.sub)}</em></button>`).join("") : '<button disabled style="color:var(--faint)">No match found</button>'; qres.classList.add("on"); }
qEl.addEventListener("input", (e) => search(e.target.value)); qres.addEventListener("click", (e) => { const b = e.target.closest("button[data-s]"); if (!b) return; qres.classList.remove("on"); qEl.value = ""; location.hash = "#" + slug(b.dataset.s); if (b.dataset.a) setTimeout(() => { const target = document.getElementById(b.dataset.a); if (target) target.scrollIntoView({ behavior: "smooth" }); }, 120); }); document.addEventListener("click", (e) => { if (!e.target.closest(".searchbox")) qres.classList.remove("on"); });
let currentSubject = null; function goHome() { currentSubject = null; document.body.classList.remove("view-subject"); history.replaceState(null, "", location.pathname); window.scrollTo(0, 0); } function route() { const h = location.hash.replace(/^#/, ""); const match = Object.keys(NOTES).find((s) => slug(s) === h); if (match) { if (currentSubject !== match) { currentSubject = match; renderSubject(match); } return; } if (h === "" || h === "home" || h === "groups" || h === "resources") { currentSubject = null; document.body.classList.remove("view-subject"); if (!h) window.scrollTo(0, 0); } } window.addEventListener("hashchange", route); renderHome(); route();
